### Health check
GET http://127.0.0.1:5000/health
Accept: application/json

### Get metrics
GET http://127.0.0.1:5000/metrics

### Get processes
GET http://127.0.0.1:5000/processes

### Add process
POST http://127.0.0.1:5000/processes
Content-Type: application/json

{
  "name": "Test Process",
  "priority": "High",
  "timestamp": "2025-06-02T16:50"
}

### Delete process (replace {id})
DELETE http://127.0.0.1:5000/processes/1
